# -*- coding: utf-8 -*-
"""Frank_example_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hl3AVolvKA5NNJGe5S7WhgntSu2e1c4k
"""

#!pip install frank

import matplotlib.pyplot as plt
import numpy as np
from frank.io import load_uvtable, save_fit
from frank.radial_fitters import FrankFitter
from frank.geometry import FitGeometryGaussian
from frank.make_figs import make_quick_fig

uvtable_filename = "/content/drive/MyDrive/Disco 1/J16120_Band7_keepflagsFalse.txt"
u, v, vis, weights = load_uvtable(uvtable_filename)

FF = FrankFitter(Rmax=1.6, N=250, geometry=FitGeometryGaussian(),
                 alpha=1.05, weights_smooth=1e-4)

sol = FF.fit(u, v, vis, weights)

fig, axes = make_quick_fig(u, v, vis, weights, sol, bin_widths=[1e3, 5e4], force_style=True)
plt.show()